name: shared_engine
description: A starting point for Dart libraries or applications.
version: 2.0.1
repository: https://github.com/dimaljay/shared_engine

environment:
  sdk: '>=3.3.3 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  firebase_database: ^11.1.1
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.2
  

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
