name: shared_engine
description: A starting point for Dart libraries or applications.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
